### PR TITLE
Fix/42 update for RStudio 1.3

### LINKED ISSUE #42: In RStudio 1.3, RStudio dictionaries are not detected
In RStudio 1.3, the directory where downloaded RStudio dictionaries are stored has changed. So `hunspell:::rstudio_dicpaths()` finds only 4 default dictionaries. Previously, it found all dictionaries installed by RStudio. Could **hunspell** be updated for RStudio 1.3?

***

**Details**

On Windows, the new directory with dictionaries is:
```r
fs::path(Sys.getenv("APPDATA"), "RStudio/dictionaries/languages-system")
```
e.g.:
```
C:/Users/User/AppData/Roaming/RStudio/dictionaries/languages-system
```
On the other OS'es, it should be (I cannot check this. More details in [this post](https://blog.rstudio.com/2020/02/18/rstudio-1-3-preview-configuration/)):
```r
fs::path_expand_r("~/.config/rstudio/dictionaries/languages-system")
```

In RStudio 1.2 or earlier, it was:
```r
fs::path(rstudioapi::userDictionariesPath(), "languages-system")
```
e.g.:
```
C:/Users/User/AppData/Local/RStudio-Desktop/dictionaries/languages-system
```

### PR DESCRIPTION
**Pull request by GegznaV**
Fixes #42

### CODE REVIEW

**Comment by GegznaV** [comment]
image


This R CMD check failure is not related to this PR, it's related to the wrong setup of Travis CI on Mac (see #44).

**Comment by jeroen** [comment]
Is there any reason you're randomly replacing quotes? That makes it more difficult to review this.

**Comment by GegznaV** [comment]
Sorry for the quotes. Instead of fixing indentation in the code I
accidentally applied tidyverse style (I pushed a wrong keybòard combination
and didn't noticed that) . I'll fix the quotes.

2020 rugs. 8, an 02:32, Jeroen Ooms <notifications@github.com> rašė:

**Comment by GegznaV** [comment]
I undid the style corrections by **styler**. Now my changes could be seen more clearly.

**Comment by GegznaV** [comment]
Close in favor of #48

**Pull request closed without merging**
