### PR TITLE
Dictionary caching and list functions

### PR DESCRIPTION
**Pull request by ireyoner**
Added:
1. Dictionary caching
2. List functions
3. Processing function (BUG: "analyze" is not working - error in strings conversion?)

### CODE REVIEW

**Comment by ireyoner** [comment]
New version is working for me when I call document(), but I get the same error as in issue #12.

**Comment by jeroenooms** [comment]
Thank you for this. There are some nice ideas in here, but it feels a bit overkill to solve a relatively small optimization problem. I rather keep the package portable and lightweight, and not drag in dependencies on CXX11, Rcpp-modules, Rcereal and BH...

Anyway I'm traveling this week, I'll have a closer look at it next week.

**Comment by ireyoner** [comment]
Well, I left those 2 imports by accident when I was trying to find why install() is not working...  My mistake. Those changes are working without them, so I don't think they are overkill now, without those imports. I fixed it in new commit.

**Comment by jeroenooms** [comment]
This still fails the tests. I implemented a more simple solution. Thanks for your PR though!

**Pull request closed without merging**
